Redesigned Details Activity. Fixed check for null.
polarxdev/PokemonsProject pull request #2
Opened 2024-06-20 12:11 UTC by polarxdev

### Design 
RelativeLayout replaced with ConstraintLayout
Added characteristics of Category and Abilities.
##Fixed check fot null
### Screenshots
![photo_2024-06-20_15-06-46](https://github.com/polarxdev/PokemonsProject/assets/172485228/2e0accad-4601-4639-bb76-a9fd6a12e613)

2024-06-21 04:56 UTC, pzinkevich42innowise requested changes

2024-06-21 04:56 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_details.xml
>          android:layout_width="match_parent"
0dp

2024-06-21 04:56 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_details.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
А зачем на этом экране вообще Constraint? Просто чтоб был?

Давай все элементы будут только внутри этого Constraint без других viewGroup

2024-06-21 17:13 UTC, polarxdev commented
#Fixed remarks

2024-06-23 19:30 UTC, pzinkevich42innowise approved these changes

2024-06-23 20:15 UTC, merged