Feature/third
polarxdev/PokemonsProject pull request #3
Opened 2024-06-29 13:04 UTC by polarxdev

### Changes
Added usage of `RecyclerView`
Added usage of `DiffUtil`
Redesigned pokemon list with use of `divider`

2024-06-29 14:20 UTC, pzinkevich42innowise requested changes

2024-06-29 14:20 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemonsproject/ListActivity.kt
> +            layoutManager = LinearLayoutManager(context)
Это вынеси в xml

2024-06-29 14:20 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemonsproject/PokemonListAdapter.kt
> +    interface Listener {
Почему не лямбда или SAM?

2024-06-30 11:23 UTC, polarxdev commented
### Added png to webp conversion

2024-06-30 12:44 UTC, pzinkevich42innowise requested changes

2024-06-30 12:44 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemonsproject/ListActivity.kt
> +class ListActivity : AppCompatActivity(), PokemonListAdapter.PokemonClickListener {
Это не лучшее решение, передай лямбдой

2024-06-30 12:44 UTC, pzinkevich42innowise commented on app/src/main/res/drawable/bulbasaur.png
А чего это ты сюда заливаешь конвертацию? Какое это отношение имеет к этому ПРу?

2024-06-30 14:04 UTC, pzinkevich42innowise approved these changes

2024-06-30 14:09 UTC, merged